kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: keystone
  labels:
    system: openstack
    type: api
    component: keystone
spec:
  replicas: 2
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: keystone


  template:
    metadata:
      labels:
        name: keystone
      annotations:
        chart-version: {{.Chart.Version}}
        checksum/etc-configmap.yaml: {{ include "keystone/templates/etc-configmap.yaml" . | sha256sum }}
        checksum/bin-configmap.yaml: {{ include "keystone/templates/bin-configmap.yaml" . | sha256sum }}
    spec:
      containers:
        - name: keystone
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-keystone-m3:{{.Values.image_version_keystone_m3}}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v3
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 15
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/keystone-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "keystone-migration,keystone-bootstrap"
            - name: DEPENDENCY_SERVICE
              value: "postgres-keystone,rabbitmq,memcached"
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
          ports:
            - name: public
              containerPort: 5000
            - name: admin
              containerPort: 35357
          volumeMounts:
            - mountPath: /keystone-etc
              name: keystone-etc
            - mountPath: /fernet-keys
              name: fernet-secret
              readOnly: true
            - mountPath: /container.init
              name: container-init
        - name: statsd
          image: prom/statsd-exporter:master
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.port_metrics}}
      volumes:
        - name: keystone-etc
          configMap:
            name: keystone-etc
        - name: fernet-secret
          secret:
            secretName: fernet-secret
        - name: container-init
          configMap:
            name: keystone-bin
