apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-etc
  labels:
    system: openstack
    type: configuration
    component: cinder

data:
  cinder.conf: |
{{ tuple "etc/_cinder.conf.tpl" . | include "template" | indent 4 }}
  policy.json: |
{{ tuple "etc/_cinder-policy.json.tpl" . | include "template" | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
