# Default values for mariadb.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: DEFINED-IN-COMPONENT-CHART
image: mariadb:10.1
port_public: 3306
#
#root_password: 
#initdb_configmap:
#persistance_claim:

backup:
  enabled: false
  repository: sapcc/backup-tools
  image_version: v0.4.1
  interval_full: 3 days
  interval_incr: 3 days
  os_auth_url: DEFINED-IN-REGION-SECRETS
  os_auth_version: DEFINED-IN-REGION-SECRETS
  os_identity_api_version: DEFINED-IN-REGION-SECRETS
  os_username: DEFINED-IN-REGION-SECRETS
  os_user_domain: DEFINED-IN-REGION-SECRETS
  os_project_name: DEFINED-IN-REGION-SECRETS
  os_project_domain: DEFINED-IN-REGION-SECRETS
  os_region_name: DEFINED-IN-REGION-SECRETS
  os_password: DEFINED-IN-REGION-SECRETS
